### ISSUE TITLE
Make the templates globally generic

### ISSUE THREAD

**Issue by WilliamMcCumstie** [openflighthpc/flight-architect#64]
Currently only `alces` employs can deploy onto `aws` using the templates. Currently the `AMI` ids are specific to our account. This means we can only deploy into `eu-west-1` and `eu-west-2`. But more importantly, no one else can deploy using these templates.

This is the offending lines in the `domainandallnodes` template:
https://github.com/alces-software/underware/blob/0a4ca1ebfa70ba2e27c153bf8ef76ba98ba2250c/data/templates/aws/domain/domainandallnodes.yaml#L12-L16

Ideally this would use the generic `AMI` id for the official `centos7` image

**Comment by ColonelPanics** [comment]
Fixed in 06c2585fe02f44ecbb59b5d0c4855143e1583df3
